### ISSUE TITLE
[Docker] Fix a Docker container

### ISSUE THREAD

**Issue by jherrlin** [Kodkollektivet/kodkollektivet.se#11]
Should we create a Docker container for this project?
Maybe it would be easy for people to start working on it if we could provide a container and instructions for how to run it?

**Comment by megamos** [comment]
Sounds lika a good plan to me. I'll happely do it soon. Just wanna get the layout and styling to an OK state first :)

**Comment by jherrlin** [comment]
Nice! Should we do a PP session together and do it maybe?

**Comment by megamos** [comment]
Lets!

**Comment by jherrlin** [comment]
Resolved in https://github.com/Kodkollektivet/kodkollektivet.se/commit/289f5d86e2be3fb0dbdb8088431adaac795a3332
