### ISSUE TITLE
Dynamic board page

### ISSUE THREAD

**Issue by jherrlin** [Kodkollektivet/kodkollektivet.se#18]
The board page is static today. Maybe that should be a dynamic view and we should have a `Board` database model. The benefit with that is that it would be easy to add new board members, their position and a photo.

**Comment by megamos** [comment]
Sounds like the way to go. All that html DID hurt my eyes as I was working on the page :)

**Comment by jherrlin** [comment]
Resolved in https://github.com/Kodkollektivet/kodkollektivet.se/pull/29
