### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by jherrlin** [Kodkollektivet/kodkollektivet.se#2]
We need some kind of design that make the site more attractive.

**Comment by jherrlin** [comment]
A preview of a work in progress site can be found here: http://207.154.218.10:8000/en/

**Comment by megamos** [comment]
Shall I start hosting the design in progress? Mentioned link is broken. I can host it on AWS. Need to set stuff up there anyways. And by doing so I might even start fixing the styling issues we have :)

**Comment by jhe10709** [comment]
I think the best way is to do the hosting by ourself's but i created a new issue about that. https://github.com/Kodkollektivet/kodkollektivet.se/issues/26

**Comment by megamos** [comment]
Close this issue, or fix current [Styling] issues first?

**Comment by ritzelpaket** [comment]
I think this can be closed. What do you think?

**Comment by megamos** [comment]
Yes lets do it. Doesn't seem relevant anymore. If we wanna redesign, we'll open a new one.
