### ISSUE TITLE
Obfuscate email strings on board page

### ISSUE THREAD

**Issue by ritzelpaket** [Kodkollektivet/kodkollektivet.se#42]
To avoid Email SPAM it seems to be a good idea to change the plain email strings from the board members to similiar unicode characters and/or generate the mail-addresses with javascript on the fly.

Other state of the art methods are welcome as well.

**Comment by jhe10709** [comment]
@ritzelpaket what about replace the `@` with `[at]` before the view is generated, this will give us the correct values in the database but obfuscated on the frontend.

**Comment by ritzelpaket** [comment]
That sounds like a good first and quick patch. But I never got why spammers could not simply replace [at] with @ back again in their database... Therefore I think we need more than that.

**Comment by jhe10709** [comment]
What about generating small images with ImageMagick? Its installed both on the production server and in the Docker environment (https://github.com/Kodkollektivet/kodkollektivet.se/blob/master/Dockerfile#L7). 

There is also a Python lib for interacting with ImageMagick called Wand (https://github.com/Kodkollektivet/kodkollektivet.se/blob/master/requirements.txt#L8). There is an example of usage here: https://github.com/Kodkollektivet/kodkollektivet.se/blob/master/kodkollektivet/kodkollektivet/models.py#L28-L32

**Comment by xoften** [comment]
Use a google reCAPTCHA?? ;) 

https://www.google.com/recaptcha/admin#mailhide

**Comment by ritzelpaket** [comment]
Bah, is google the holy answer to everything? ^^

**Comment by ritzelpaket** [comment]
Generating images is also a good idea. We do not have "customers" so people which want to write us, can take the extra step of writing the email-address into their mail client.

**Comment by xoften** [comment]
True and then we surely have something that a crawler cant read :)

**Comment by ritzelpaket** [comment]
@xoften Is there an open source captcha you know about?

**Comment by xoften** [comment]
no clue really :/ https://visualcaptcha.net/ maybe?

**Comment by jherrlin** [comment]
This was fixed in https://github.com/Kodkollektivet/kodkollektivet.se/pull/59 with Wand and ImageMagick
